// Source tier scoring configuration — single authoritative source
// Used by quality-score.cjs and all content fix scripts
const SOURCE_TIER_SCORE = {
  'academic_paper':         10,
  'peer_reviewed':          10,
  'journal':                 9,
  'conference':              9,
  'survey_paper':           10,
  'paper':                  10,
  'preprint':               10,
  'thesis':                 10,
  'dissertation':           10,
  'textbook':                8,
  'reference':               7,
  'literature':              7,
  'knowledge_base':          5,
  'patent':                  8,
  'whitepaper':              7,
  'official_report':         7,
  'technical_report':        7,
  'report':                  6,
  'standard':                8,
  'rulebook':                7,
  'specification':           8,
  'course_material':         6,
  'official_documentation':  7,
  'documentation':           6,
  'manual':                  6,
  'repository':              5,
  'database':                5,
  'data_source':             5,
  'technical_book':          8,
  'book':                    6,
  'book_chapter':            6,
  'benchmark':               6,
  'framework':               5,
  'blog_post':               4,
  'tutorial':                4,
  'news_article':            4,
  'announcement':            4,
  'article':                 4,
  'comparison':              4,
  'tracker':                 4,
  'periodical':              5,
  'encyclopedia':            3,
  'website':                 3,
  'wiki':                    1,
  'other':                   3,
};

module.exports = { SOURCE_TIER_SCORE };
